// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserInfoAPI.Models;

namespace UserInfoAPI.Migrations
{
    [DbContext(typeof(UserInfoDbContext))]
    [Migration("20220225025308_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InterestRentee", b =>
                {
                    b.Property<int>("InterestsIntId")
                        .HasColumnType("int");

                    b.Property<string>("RenteesUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InterestsIntId", "RenteesUserId");

                    b.HasIndex("RenteesUserId");

                    b.ToTable("InterestRentee");
                });

            modelBuilder.Entity("UserInfoAPI.Models.Interest", b =>
                {
                    b.Property<int>("IntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            IntId = 1,
                            IntName = "Cafe-hopping"
                        },
                        new
                        {
                            IntId = 2,
                            IntName = "Pottery-making"
                        });
                });

            modelBuilder.Entity("UserInfoAPI.Models.Rentee", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Rentees");

                    b.HasData(
                        new
                        {
                            UserId = "elicam@email.com",
                            About = "Call me queen.",
                            DOB = new DateTime(1974, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 20.0,
                            FullName = "Elizabeth Cambridge",
                            Gender = "Female",
                            IsActive = true,
                            NickName = "Eli"
                        },
                        new
                        {
                            UserId = "philc@email.com",
                            About = "Call me king.",
                            DOB = new DateTime(1974, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fee = 20.0,
                            FullName = "Phillip Cambridge",
                            Gender = "Male",
                            IsActive = false,
                            NickName = "Phil"
                        });
                });

            modelBuilder.Entity("UserInfoAPI.Models.Renter", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Renters");

                    b.HasData(
                        new
                        {
                            UserId = "johndoe@email.com",
                            About = "Will call you queen.",
                            DOB = new DateTime(1974, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "John Doe",
                            Gender = "Male",
                            IsActive = true,
                            NickName = "John"
                        },
                        new
                        {
                            UserId = "janedoe@email.com",
                            About = "Will call you king.",
                            DOB = new DateTime(1974, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Jane Doe",
                            Gender = "Female",
                            IsActive = false,
                            NickName = "Jane"
                        });
                });

            modelBuilder.Entity("InterestRentee", b =>
                {
                    b.HasOne("UserInfoAPI.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsIntId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserInfoAPI.Models.Rentee", null)
                        .WithMany()
                        .HasForeignKey("RenteesUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
